### ISSUE TITLE
Can I use Turtlebot3 Burger on this demo automatic_parking_vision?

### ISSUE THREAD

**Issue by ilhamasy** [ROBOTIS-GIT/turtlebot3_applications#31]
![screenshot from 2018-11-07 00-43-41](https://user-images.githubusercontent.com/28057742/48082887-4b042e80-e226-11e8-9566-295835068946.png)

And I run in the terminal 
$ export TURTLEBOT3_MODEL=waffle_pi
$ roslaunch turtlebot3_automatic_parking_vision turtlebot3_automatic_parking_vision.launch

first look on the terminal nothing error but my turtlebot just spinning arround and can't go to the target, and finally getting the error
![screenshot from 2018-11-06 21-39-46](https://user-images.githubusercontent.com/28057742/48083158-075df480-e227-11e8-9041-bfa25ac0671c.png)
![screenshot from 2018-11-06 20-30-25](https://user-images.githubusercontent.com/28057742/48083216-31171b80-e227-11e8-8488-8e589d44b0b6.png)

please help :( 
fyi, i use turtlebot3 burger; OS SBC :raspbian; OS REMOTE_PC: UBUNTU_16.04

**Comment by kijongGil** [comment]
Hi @ilhamasy :)
What did you use AR_maker ID? This package is default AR_maker ID 17.
This error is cant find AR maker.

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
