### ISSUE TITLE
Can I use 2 camera, so uses 2 raspberry pi on this demo automatic_parking_vision? 

### ISSUE THREAD

**Issue by ilhamasy** [ROBOTIS-GIT/turtlebot3_applications#32]

**Comment by kijongGil** [comment]
Hi @ilhamasy :)
You mean that you have two turtlebot3?

**Comment by ilhamasy** [comment]
No, i mean use 2 raspberry pi in one turtlebot. So, that raspberry camera
modul just one raspberry pi and i want use 2 camera raspberry pi modul. Is
that possible to this demo?

**Comment by kijongGil** [comment]
It can't use 2 camera. This package is use one camera topic. If you want to two camera, you have to separate camera topic and modify many thing in code.

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
