### ISSUE TITLE
Automatic Parking Vision problems

### ISSUE THREAD

**Issue by DynamicalNAV** [ROBOTIS-GIT/turtlebot3_applications#34]
Hello Sir/Madam,

I have installed your turtlebot3 application packages, I follow the instructions provided on the website, everything shows up with no errors, however when I run the turtlebot3_automatic_parking_vision package, no errors, the robot detects the AR tags, but it keeps on rotating and does not stop to correct its angle to move in the desired directions. Is there any possible advice to give or do you know of anything in particular to change in the automatic_parking_vision node?

Secondly the bigger goal of this is that I am mainly using this package to implement a mass-spring-damper system for the turtlebot3. This is where the turtlebot3 waffle_pi detects the marker and aligns itself to the marker just like the first part of the automatic parking vision algorithm, but this time the control law is to maintain a distance of 50cm away from tracker using full state feedback controller. Do you recommend changing the FnGoStraightpart, or do you recommend creating a new method to move towards to goal, or any other suggestions?

Kindest Regards,
DynamicalNAV

**Comment by RyanJaehyunShim** [comment]
@DynamicalNAV 

Sorry for the late reply. Our team has been working on the issue but we haven't figured out any solutions to it yet. We sincerely apologize for the long wait and we will add another comment again with a proper answer as soon as possible.

As to the second question, we do not support other than basic functions we provide and explained about on our e-manual. However, I believe you can get some clues from IEEE papers (or even contacting the relevant authors could give you an answer you are looking for) 

Good luck with your work,
Ryan

**Comment by ROBOTIS-Kayman** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by siewwing** [comment]
Hi, 
I faced the same problem DynamicalNAV. The program is able to detect the AR tag. But it just kept going round and round, and not move towards the AR tag in real environment. How to solve this?

**Comment by jcotof** [comment]
Hello, I have the same problem and I would like to know if you could solve it? thank you.

**Comment by rjshim** [comment]
@DynamicalNAV @siewwing @jcotof 

Print out AR marker 17 which is the most right bottom one from the [link](http://wiki.ros.org/ar_track_alvar?action=AttachFile&do=view&target=markers9to17.png). The marker should be as big as the one in this instruction [video](https://www.youtube.com/watch?v=dvpWdrD3bVs) (but doesn't necessarily mean it has to be exactly the same size) Follow the instruction written at the [link](http://emanual.robotis.com/docs/en/platform/turtlebot3/applications/#automatic-parking-vision) and let me know if you still see the same problem.

Regards.,
Ryan

**Comment by jcotof** [comment]
Thank you very much Ryan, I have the burger and install a camera, is
the processor enough to use this method or is the method with the
reflective tape better?

I take this opportunity to ask you another question.
I want the robot to follow a path on my map, I am changing the initial
position of my robot when I start using:
pub = rospy.Publisher ('/ initialpose', PoseWithCovarianceStamped,
queue_size = 10), but at the end of the whole path, the robot returns
to position (0,0), what is my mistake?

[image: imagen.png]

I'm starting with ROS, I appreciate your help !!!

Julio

**Comment by rjshim** [comment]
@jcotof  

It has nothing to do with which model you use since all models use rasberrypi3 + OpenCR. 

As for the second question, don't leave it here if it is not related to vision parking. Give us more details about the problem (Btw, the link to the image is also broken).

Test as I explained above and let me know if it doesn't work
Ryan

**Comment by jcotof** [comment]
Thank you Ryan, i have followed the instructions, the burger cannot
find the image and does not stop rotating and the following error is
shown:

process[joint_state_publisher-1]: started with pid [3062]
process[robot_state_publisher-2]: started with pid [3063]
process[rviz-3]: started with pid [3064]
process[camera_rgb_optical_frame_to_cam-4]: started with pid [3065]
process[ar_track_alvar-5]: started with pid [3080]
process[automatic_parking_vision-6]: started with pid [3089]
[ INFO] [1570806622.660661048]: Subscribing to info topic
[ INFO] [1570806622.703689523]: AR tracker reconfigured: ENABLED 8.00
8.00 0.08 0.20
[*ERROR] [1570806625.258573597]: Could not find a connection between
'base_footprint' and 'camera' because they are not part of the same
tree.Tf has two or more unconnected trees.*

**Comment by rjshim** [comment]
@jcotof 

This package only supports waffle models. You can still use this package with a burger but it won't be parked at the right location. Try below (it still works but with wrong tf info).
$ export TURTLEBOT3_MODEL=waffle_pi
then,
$ roslaunch turtlebot3_automatic_parking_vision turtlebot3_automatic_parking_vision.launch

**Comment by jcotof** [comment]
I already tried and as you say, do not park in the right place. Will
you have an updated package for burger in the future? I will have the
same problem if I try Automatic Parking
(reflective tape) ?

**Comment by rjshim** [comment]
@jcot

Currently, we have no concrete plan for supporting this package for the burger model for ROS Kinetic (but maybe yes for ROS2 Dashing in the near future). 

>  I will have the same problem if I try Automatic Parking

yeah, that package also only support the waffle models.

Regards,
Ryan

**Comment by rjshim** [comment]
As there have been no updates, I am closing this issue.
