### ISSUE TITLE
Ar marker not detected

### ISSUE THREAD

**Issue by priyablue** [ROBOTIS-GIT/turtlebot3_applications#36]
Hi, 

we are working on automatic parking vision with waffle_pi as per the instruction guided in the e-manual. Firstly, after launching the turtlebot3_automatic_parking_vision command, the robot is able to detect the armarker but not able to review with id or its name (ar_maker as shown in video in rviz). Can you let me know have i missed any package or any other modifications has to be made in the code.  

Secondly when it started to move, its continuously rotating in a same place and not detecting the ar marker that is pasted on the wall. 

Can you please consider and let us know why is this problem, and what has to be modified in the source code.

**Comment by RyanJaehyunShim** [comment]
@priyablue 

Our team is aware of the issue and we are working on it. We will update it in the near future so please skip it first unless you are working on a project using the automatic vision parking package.

Regards,
Ryan

**Comment by priyablue** [comment]
Thanks for the response.

But we are in need of this problem to be rectified as this a main part of
our project. So kindly let me know what is the trobleshooting to be made
as early as possible.

I request you to take this in a priority basis. Thanks & Regards

**Comment by RyanJaehyunShim** [comment]
@priyablue 

As for the first question, you should use a specific AR marker (id: 17) for it. Please find it in the link below
(http://wiki.ros.org/ar_track_alvar)

Unfortunately, we have not figured out the reason causing the problem you mentioned your question. It will be really appreciated if you can find the reason while working on your project and make a contribution to our package.

Thank you,
Ryan

**Comment by priyablue** [comment]
Thanks for your reply.

 As we are the official distributor of Robotis, it would be great if your
share your technical team contact personally as we are having many such
working packages and wishing to contribute it to Robotis community. You can
direct your technical team to contact us at info@bluetronics.co.in.

Note: this is for a Not-For-Profit cause.

Thanks & Regards

**Comment by RyanJaehyunShim** [comment]
@priyablue 

Please send an email with details to jhshim@robotis.com and kmjung@robotis.com and I will close this issue.

Thank you,
Ryan

**Comment by priyablue** [comment]
Thanks.  Will send email correspondingly.   If the error related to
rotating of Robot is solved. Please reopen this issue and update the
modifications.

Thanks

**Comment by priyablue** [comment]
Hello,

The marker that you have used to demonstrate in the automatic parking
vision video, can you please tell me the id of the marker is used.

When you insisted me to use 17 I'd. It seems different when comparing with
the demo video.

Kindly guide.

**Comment by RyanJaehyunShim** [comment]
@priyablue 

Please fInd the id 17 AR marker in the link I sent to you and use it (you can easily check it through opening source code file in the package). The marker in the video is outdated.

Regards,
Ryan
