### ISSUE TITLE
Modified design burger never reach the goal

### ISSUE THREAD

**Issue by jcotof** [ROBOTIS-GIT/turtlebot3_applications#40]
Good evening, I have modified the design of my burger to install additional  equipment, I separated the wheels, modified the height, I made it longer, etc. Additionally, the footprint parameter has also been modified according to the approximate dimensions in the costmap_common_params_burger.yaml file.
My problem is that now when  I send the robot to 2d nav gold in Rviz the burger never reach it and moves from one place to another without being able reach the goal.

How can I solved this problem ?  thanks for your help

**Comment by ROBOTIS-Will** [comment]
@jcotof 
Hi,
When you are modifying the hardware design, you also need to modify the parameter that describes the robot in the source code and OpenCR firmware.
https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/examples/turtlebot3_waffle/turtlebot3_core/turtlebot3_waffle.h#L24
Thank you.
