### ISSUE TITLE
Avoiding obstacles move_base package

### ISSUE THREAD

**Issue by jcotof** [ROBOTIS-GIT/turtlebot3_applications#42]
Hello, your help please,Is there any example about how to use data from laser and IR/ultrasonic Sensor together to avoid obstacles with move_base package?

**Comment by ROBOTIS-Will** [comment]
@jcotof 
Hi, I believe the you should be able to provide sufficient information to local costmap with your sensor so that local planner can modify the local path regarding the detected obstacle. Please see [move_base](http://wiki.ros.org/move_base) package for more details.

**Comment by ROBOTIS-Will** [comment]
This issue will be closed since there were no actions for a while. Please feel free to reopen this issue when necessary. Thanks.
