### ISSUE TITLE
Follow Filter don't work anymore

### ISSUE THREAD

**Issue by bc2606** [ROBOTIS-GIT/turtlebot3_applications#44]
When launching follow filter the following error happens.

`terminate called after throwing an instance of 'ros::InvalidNameException'
  what():  Character [ ] at element [6] is not valid in Graph Resource Name [~exist intensity 500 to 4000].  Valid characters are a-z, A-Z, 0-9, / and _.`

The installation is new on a ubuntu 18.04.4.
I don't know where it can come from.

Is it a known issue? 

Thanks in advance for your help.

**Comment by BastianKrammer** [comment]
I got the same issue, do you found a solution to this?

**Comment by sherief-adsafe** [comment]
check on the YAML file , the name parameter should not contain any spaces .
